---
name: Test E2E
description: Run e2e tests
inputs:
  working_directory:
    description: "Working directory"
    required: false
    default: .
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: neptune-ai/neptune-detectron2
        path: ${{ inputs.working_directory }}

    - name: Upgrade pip
      run: python -m pip install --upgrade pip
      shell: bash

    - name: Install dependencies
      working-directory: ${{ inputs.working_directory }}
      run: pip install -e .[dev]
      shell: bash

    - name: Install detectron2 (ubuntu)
      if: ${{ runner.os != 'macOS'}}
      working-directory: ${{ inputs.working_directory }}
      run: python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
      shell: bash

    - name: Install detectron2 (macOS)
      if: ${{ runner.os == 'macOS'}}
      working-directory: ${{ inputs.working_directory }}
      run: CC=clang CXX=clang++ ARCHFLAGS="-arch x86_64" python -m pip install -U 'git+https://github.com/facebookresearch/detectron2.git' --no-build-isolation
      shell: bash

    - name: Run tests
      working-directory: ${{ inputs.working_directory }}
      run: pytest -v --doctest-modules
      shell: bash
